// Generated by dia2code
#ifndef __REST__H
#define __REST__H

#include "rest/HttpStatus.h"
#include "rest/AbstractService.h"
#include "rest/PlayerService.h"
#include "rest/VersionService.h"
#include "rest/ServiceException.h"
#include "rest/ServicesManager.h"
#endif
