# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/timkrief/Nextcloud/Ordinateur/Documents/ENSEA/3A/projet/kriefdejeangeorges

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/timkrief/Nextcloud/Ordinateur/Documents/ENSEA/3A/projet/kriefdejeangeorges

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timkrief/Nextcloud/Ordinateur/Documents/ENSEA/3A/projet/kriefdejeangeorges/CMakeFiles /home/timkrief/Nextcloud/Ordinateur/Documents/ENSEA/3A/projet/kriefdejeangeorges/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timkrief/Nextcloud/Ordinateur/Documents/ENSEA/3A/projet/kriefdejeangeorges/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

src/client/main.o: src/client/main.cpp.o

.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i

.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s

.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/client/render/EventController.o: src/client/render/EventController.cpp.o

.PHONY : src/client/render/EventController.o

# target to build an object file
src/client/render/EventController.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/EventController.cpp.o
.PHONY : src/client/render/EventController.cpp.o

src/client/render/EventController.i: src/client/render/EventController.cpp.i

.PHONY : src/client/render/EventController.i

# target to preprocess a source file
src/client/render/EventController.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/EventController.cpp.i
.PHONY : src/client/render/EventController.cpp.i

src/client/render/EventController.s: src/client/render/EventController.cpp.s

.PHONY : src/client/render/EventController.s

# target to generate assembly for a file
src/client/render/EventController.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/EventController.cpp.s
.PHONY : src/client/render/EventController.cpp.s

src/client/render/GFieldObject.o: src/client/render/GFieldObject.cpp.o

.PHONY : src/client/render/GFieldObject.o

# target to build an object file
src/client/render/GFieldObject.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GFieldObject.cpp.o
.PHONY : src/client/render/GFieldObject.cpp.o

src/client/render/GFieldObject.i: src/client/render/GFieldObject.cpp.i

.PHONY : src/client/render/GFieldObject.i

# target to preprocess a source file
src/client/render/GFieldObject.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GFieldObject.cpp.i
.PHONY : src/client/render/GFieldObject.cpp.i

src/client/render/GFieldObject.s: src/client/render/GFieldObject.cpp.s

.PHONY : src/client/render/GFieldObject.s

# target to generate assembly for a file
src/client/render/GFieldObject.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GFieldObject.cpp.s
.PHONY : src/client/render/GFieldObject.cpp.s

src/client/render/GMap.o: src/client/render/GMap.cpp.o

.PHONY : src/client/render/GMap.o

# target to build an object file
src/client/render/GMap.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GMap.cpp.o
.PHONY : src/client/render/GMap.cpp.o

src/client/render/GMap.i: src/client/render/GMap.cpp.i

.PHONY : src/client/render/GMap.i

# target to preprocess a source file
src/client/render/GMap.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GMap.cpp.i
.PHONY : src/client/render/GMap.cpp.i

src/client/render/GMap.s: src/client/render/GMap.cpp.s

.PHONY : src/client/render/GMap.s

# target to generate assembly for a file
src/client/render/GMap.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GMap.cpp.s
.PHONY : src/client/render/GMap.cpp.s

src/client/render/GPlayer.o: src/client/render/GPlayer.cpp.o

.PHONY : src/client/render/GPlayer.o

# target to build an object file
src/client/render/GPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GPlayer.cpp.o
.PHONY : src/client/render/GPlayer.cpp.o

src/client/render/GPlayer.i: src/client/render/GPlayer.cpp.i

.PHONY : src/client/render/GPlayer.i

# target to preprocess a source file
src/client/render/GPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GPlayer.cpp.i
.PHONY : src/client/render/GPlayer.cpp.i

src/client/render/GPlayer.s: src/client/render/GPlayer.cpp.s

.PHONY : src/client/render/GPlayer.s

# target to generate assembly for a file
src/client/render/GPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GPlayer.cpp.s
.PHONY : src/client/render/GPlayer.cpp.s

src/client/render/GRender.o: src/client/render/GRender.cpp.o

.PHONY : src/client/render/GRender.o

# target to build an object file
src/client/render/GRender.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GRender.cpp.o
.PHONY : src/client/render/GRender.cpp.o

src/client/render/GRender.i: src/client/render/GRender.cpp.i

.PHONY : src/client/render/GRender.i

# target to preprocess a source file
src/client/render/GRender.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GRender.cpp.i
.PHONY : src/client/render/GRender.cpp.i

src/client/render/GRender.s: src/client/render/GRender.cpp.s

.PHONY : src/client/render/GRender.s

# target to generate assembly for a file
src/client/render/GRender.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GRender.cpp.s
.PHONY : src/client/render/GRender.cpp.s

src/client/render/GState.o: src/client/render/GState.cpp.o

.PHONY : src/client/render/GState.o

# target to build an object file
src/client/render/GState.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GState.cpp.o
.PHONY : src/client/render/GState.cpp.o

src/client/render/GState.i: src/client/render/GState.cpp.i

.PHONY : src/client/render/GState.i

# target to preprocess a source file
src/client/render/GState.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GState.cpp.i
.PHONY : src/client/render/GState.cpp.i

src/client/render/GState.s: src/client/render/GState.cpp.s

.PHONY : src/client/render/GState.s

# target to generate assembly for a file
src/client/render/GState.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/GState.cpp.s
.PHONY : src/client/render/GState.cpp.s

src/client/render/TextureManager.o: src/client/render/TextureManager.cpp.o

.PHONY : src/client/render/TextureManager.o

# target to build an object file
src/client/render/TextureManager.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/TextureManager.cpp.o
.PHONY : src/client/render/TextureManager.cpp.o

src/client/render/TextureManager.i: src/client/render/TextureManager.cpp.i

.PHONY : src/client/render/TextureManager.i

# target to preprocess a source file
src/client/render/TextureManager.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/TextureManager.cpp.i
.PHONY : src/client/render/TextureManager.cpp.i

src/client/render/TextureManager.s: src/client/render/TextureManager.cpp.s

.PHONY : src/client/render/TextureManager.s

# target to generate assembly for a file
src/client/render/TextureManager.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/TextureManager.cpp.s
.PHONY : src/client/render/TextureManager.cpp.s

src/client/tests.o: src/client/tests.cpp.o

.PHONY : src/client/tests.o

# target to build an object file
src/client/tests.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/tests.cpp.o
.PHONY : src/client/tests.cpp.o

src/client/tests.i: src/client/tests.cpp.i

.PHONY : src/client/tests.i

# target to preprocess a source file
src/client/tests.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/tests.cpp.i
.PHONY : src/client/tests.cpp.i

src/client/tests.s: src/client/tests.cpp.s

.PHONY : src/client/tests.s

# target to generate assembly for a file
src/client/tests.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/tests.cpp.s
.PHONY : src/client/tests.cpp.s

src/server/main.o: src/server/main.cpp.o

.PHONY : src/server/main.o

# target to build an object file
src/server/main.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.o
.PHONY : src/server/main.cpp.o

src/server/main.i: src/server/main.cpp.i

.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s

.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

src/shared/ai/CPU.o: src/shared/ai/CPU.cpp.o

.PHONY : src/shared/ai/CPU.o

# target to build an object file
src/shared/ai/CPU.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/CPU.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/CPU.cpp.o
.PHONY : src/shared/ai/CPU.cpp.o

src/shared/ai/CPU.i: src/shared/ai/CPU.cpp.i

.PHONY : src/shared/ai/CPU.i

# target to preprocess a source file
src/shared/ai/CPU.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/CPU.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/CPU.cpp.i
.PHONY : src/shared/ai/CPU.cpp.i

src/shared/ai/CPU.s: src/shared/ai/CPU.cpp.s

.PHONY : src/shared/ai/CPU.s

# target to generate assembly for a file
src/shared/ai/CPU.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/CPU.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/CPU.cpp.s
.PHONY : src/shared/ai/CPU.cpp.s

src/shared/ai/DeepCPU.o: src/shared/ai/DeepCPU.cpp.o

.PHONY : src/shared/ai/DeepCPU.o

# target to build an object file
src/shared/ai/DeepCPU.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/DeepCPU.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/DeepCPU.cpp.o
.PHONY : src/shared/ai/DeepCPU.cpp.o

src/shared/ai/DeepCPU.i: src/shared/ai/DeepCPU.cpp.i

.PHONY : src/shared/ai/DeepCPU.i

# target to preprocess a source file
src/shared/ai/DeepCPU.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/DeepCPU.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/DeepCPU.cpp.i
.PHONY : src/shared/ai/DeepCPU.cpp.i

src/shared/ai/DeepCPU.s: src/shared/ai/DeepCPU.cpp.s

.PHONY : src/shared/ai/DeepCPU.s

# target to generate assembly for a file
src/shared/ai/DeepCPU.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/DeepCPU.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/DeepCPU.cpp.s
.PHONY : src/shared/ai/DeepCPU.cpp.s

src/shared/ai/DeepCPU_2.o: src/shared/ai/DeepCPU_2.cpp.o

.PHONY : src/shared/ai/DeepCPU_2.o

# target to build an object file
src/shared/ai/DeepCPU_2.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/DeepCPU_2.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/DeepCPU_2.cpp.o
.PHONY : src/shared/ai/DeepCPU_2.cpp.o

src/shared/ai/DeepCPU_2.i: src/shared/ai/DeepCPU_2.cpp.i

.PHONY : src/shared/ai/DeepCPU_2.i

# target to preprocess a source file
src/shared/ai/DeepCPU_2.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/DeepCPU_2.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/DeepCPU_2.cpp.i
.PHONY : src/shared/ai/DeepCPU_2.cpp.i

src/shared/ai/DeepCPU_2.s: src/shared/ai/DeepCPU_2.cpp.s

.PHONY : src/shared/ai/DeepCPU_2.s

# target to generate assembly for a file
src/shared/ai/DeepCPU_2.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/DeepCPU_2.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/DeepCPU_2.cpp.s
.PHONY : src/shared/ai/DeepCPU_2.cpp.s

src/shared/ai/HeuristicCPU.o: src/shared/ai/HeuristicCPU.cpp.o

.PHONY : src/shared/ai/HeuristicCPU.o

# target to build an object file
src/shared/ai/HeuristicCPU.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/HeuristicCPU.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/HeuristicCPU.cpp.o
.PHONY : src/shared/ai/HeuristicCPU.cpp.o

src/shared/ai/HeuristicCPU.i: src/shared/ai/HeuristicCPU.cpp.i

.PHONY : src/shared/ai/HeuristicCPU.i

# target to preprocess a source file
src/shared/ai/HeuristicCPU.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/HeuristicCPU.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/HeuristicCPU.cpp.i
.PHONY : src/shared/ai/HeuristicCPU.cpp.i

src/shared/ai/HeuristicCPU.s: src/shared/ai/HeuristicCPU.cpp.s

.PHONY : src/shared/ai/HeuristicCPU.s

# target to generate assembly for a file
src/shared/ai/HeuristicCPU.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/HeuristicCPU.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/HeuristicCPU.cpp.s
.PHONY : src/shared/ai/HeuristicCPU.cpp.s

src/shared/ai/RandomCPU.o: src/shared/ai/RandomCPU.cpp.o

.PHONY : src/shared/ai/RandomCPU.o

# target to build an object file
src/shared/ai/RandomCPU.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/RandomCPU.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/RandomCPU.cpp.o
.PHONY : src/shared/ai/RandomCPU.cpp.o

src/shared/ai/RandomCPU.i: src/shared/ai/RandomCPU.cpp.i

.PHONY : src/shared/ai/RandomCPU.i

# target to preprocess a source file
src/shared/ai/RandomCPU.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/RandomCPU.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/RandomCPU.cpp.i
.PHONY : src/shared/ai/RandomCPU.cpp.i

src/shared/ai/RandomCPU.s: src/shared/ai/RandomCPU.cpp.s

.PHONY : src/shared/ai/RandomCPU.s

# target to generate assembly for a file
src/shared/ai/RandomCPU.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/ai/RandomCPU.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/ai/RandomCPU.cpp.s
.PHONY : src/shared/ai/RandomCPU.cpp.s

src/shared/engine/Command.o: src/shared/engine/Command.cpp.o

.PHONY : src/shared/engine/Command.o

# target to build an object file
src/shared/engine/Command.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/engine/Command.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/engine/Command.cpp.o
.PHONY : src/shared/engine/Command.cpp.o

src/shared/engine/Command.i: src/shared/engine/Command.cpp.i

.PHONY : src/shared/engine/Command.i

# target to preprocess a source file
src/shared/engine/Command.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/engine/Command.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/engine/Command.cpp.i
.PHONY : src/shared/engine/Command.cpp.i

src/shared/engine/Command.s: src/shared/engine/Command.cpp.s

.PHONY : src/shared/engine/Command.s

# target to generate assembly for a file
src/shared/engine/Command.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/engine/Command.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/engine/Command.cpp.s
.PHONY : src/shared/engine/Command.cpp.s

src/shared/engine/CommandEndTurn.o: src/shared/engine/CommandEndTurn.cpp.o

.PHONY : src/shared/engine/CommandEndTurn.o

# target to build an object file
src/shared/engine/CommandEndTurn.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/engine/CommandEndTurn.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/engine/CommandEndTurn.cpp.o
.PHONY : src/shared/engine/CommandEndTurn.cpp.o

src/shared/engine/CommandEndTurn.i: src/shared/engine/CommandEndTurn.cpp.i

.PHONY : src/shared/engine/CommandEndTurn.i

# target to preprocess a source file
src/shared/engine/CommandEndTurn.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/engine/CommandEndTurn.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/engine/CommandEndTurn.cpp.i
.PHONY : src/shared/engine/CommandEndTurn.cpp.i

src/shared/engine/CommandEndTurn.s: src/shared/engine/CommandEndTurn.cpp.s

.PHONY : src/shared/engine/CommandEndTurn.s

# target to generate assembly for a file
src/shared/engine/CommandEndTurn.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/engine/CommandEndTurn.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/engine/CommandEndTurn.cpp.s
.PHONY : src/shared/engine/CommandEndTurn.cpp.s

src/shared/engine/CommandMove.o: src/shared/engine/CommandMove.cpp.o

.PHONY : src/shared/engine/CommandMove.o

# target to build an object file
src/shared/engine/CommandMove.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/engine/CommandMove.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/engine/CommandMove.cpp.o
.PHONY : src/shared/engine/CommandMove.cpp.o

src/shared/engine/CommandMove.i: src/shared/engine/CommandMove.cpp.i

.PHONY : src/shared/engine/CommandMove.i

# target to preprocess a source file
src/shared/engine/CommandMove.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/engine/CommandMove.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/engine/CommandMove.cpp.i
.PHONY : src/shared/engine/CommandMove.cpp.i

src/shared/engine/CommandMove.s: src/shared/engine/CommandMove.cpp.s

.PHONY : src/shared/engine/CommandMove.s

# target to generate assembly for a file
src/shared/engine/CommandMove.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/engine/CommandMove.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/engine/CommandMove.cpp.s
.PHONY : src/shared/engine/CommandMove.cpp.s

src/shared/engine/GameEngine.o: src/shared/engine/GameEngine.cpp.o

.PHONY : src/shared/engine/GameEngine.o

# target to build an object file
src/shared/engine/GameEngine.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/engine/GameEngine.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/engine/GameEngine.cpp.o
.PHONY : src/shared/engine/GameEngine.cpp.o

src/shared/engine/GameEngine.i: src/shared/engine/GameEngine.cpp.i

.PHONY : src/shared/engine/GameEngine.i

# target to preprocess a source file
src/shared/engine/GameEngine.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/engine/GameEngine.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/engine/GameEngine.cpp.i
.PHONY : src/shared/engine/GameEngine.cpp.i

src/shared/engine/GameEngine.s: src/shared/engine/GameEngine.cpp.s

.PHONY : src/shared/engine/GameEngine.s

# target to generate assembly for a file
src/shared/engine/GameEngine.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/engine/GameEngine.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/engine/GameEngine.cpp.s
.PHONY : src/shared/engine/GameEngine.cpp.s

src/shared/state/Building.o: src/shared/state/Building.cpp.o

.PHONY : src/shared/state/Building.o

# target to build an object file
src/shared/state/Building.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Building.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Building.cpp.o
.PHONY : src/shared/state/Building.cpp.o

src/shared/state/Building.i: src/shared/state/Building.cpp.i

.PHONY : src/shared/state/Building.i

# target to preprocess a source file
src/shared/state/Building.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Building.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Building.cpp.i
.PHONY : src/shared/state/Building.cpp.i

src/shared/state/Building.s: src/shared/state/Building.cpp.s

.PHONY : src/shared/state/Building.s

# target to generate assembly for a file
src/shared/state/Building.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Building.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Building.cpp.s
.PHONY : src/shared/state/Building.cpp.s

src/shared/state/Card.o: src/shared/state/Card.cpp.o

.PHONY : src/shared/state/Card.o

# target to build an object file
src/shared/state/Card.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Card.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Card.cpp.o
.PHONY : src/shared/state/Card.cpp.o

src/shared/state/Card.i: src/shared/state/Card.cpp.i

.PHONY : src/shared/state/Card.i

# target to preprocess a source file
src/shared/state/Card.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Card.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Card.cpp.i
.PHONY : src/shared/state/Card.cpp.i

src/shared/state/Card.s: src/shared/state/Card.cpp.s

.PHONY : src/shared/state/Card.s

# target to generate assembly for a file
src/shared/state/Card.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Card.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Card.cpp.s
.PHONY : src/shared/state/Card.cpp.s

src/shared/state/Cards.o: src/shared/state/Cards.cpp.o

.PHONY : src/shared/state/Cards.o

# target to build an object file
src/shared/state/Cards.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Cards.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Cards.cpp.o
.PHONY : src/shared/state/Cards.cpp.o

src/shared/state/Cards.i: src/shared/state/Cards.cpp.i

.PHONY : src/shared/state/Cards.i

# target to preprocess a source file
src/shared/state/Cards.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Cards.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Cards.cpp.i
.PHONY : src/shared/state/Cards.cpp.i

src/shared/state/Cards.s: src/shared/state/Cards.cpp.s

.PHONY : src/shared/state/Cards.s

# target to generate assembly for a file
src/shared/state/Cards.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Cards.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Cards.cpp.s
.PHONY : src/shared/state/Cards.cpp.s

src/shared/state/Deck.o: src/shared/state/Deck.cpp.o

.PHONY : src/shared/state/Deck.o

# target to build an object file
src/shared/state/Deck.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Deck.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Deck.cpp.o
.PHONY : src/shared/state/Deck.cpp.o

src/shared/state/Deck.i: src/shared/state/Deck.cpp.i

.PHONY : src/shared/state/Deck.i

# target to preprocess a source file
src/shared/state/Deck.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Deck.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Deck.cpp.i
.PHONY : src/shared/state/Deck.cpp.i

src/shared/state/Deck.s: src/shared/state/Deck.cpp.s

.PHONY : src/shared/state/Deck.s

# target to generate assembly for a file
src/shared/state/Deck.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Deck.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Deck.cpp.s
.PHONY : src/shared/state/Deck.cpp.s

src/shared/state/EquipmentCard.o: src/shared/state/EquipmentCard.cpp.o

.PHONY : src/shared/state/EquipmentCard.o

# target to build an object file
src/shared/state/EquipmentCard.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/EquipmentCard.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/EquipmentCard.cpp.o
.PHONY : src/shared/state/EquipmentCard.cpp.o

src/shared/state/EquipmentCard.i: src/shared/state/EquipmentCard.cpp.i

.PHONY : src/shared/state/EquipmentCard.i

# target to preprocess a source file
src/shared/state/EquipmentCard.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/EquipmentCard.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/EquipmentCard.cpp.i
.PHONY : src/shared/state/EquipmentCard.cpp.i

src/shared/state/EquipmentCard.s: src/shared/state/EquipmentCard.cpp.s

.PHONY : src/shared/state/EquipmentCard.s

# target to generate assembly for a file
src/shared/state/EquipmentCard.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/EquipmentCard.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/EquipmentCard.cpp.s
.PHONY : src/shared/state/EquipmentCard.cpp.s

src/shared/state/Factory.o: src/shared/state/Factory.cpp.o

.PHONY : src/shared/state/Factory.o

# target to build an object file
src/shared/state/Factory.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Factory.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Factory.cpp.o
.PHONY : src/shared/state/Factory.cpp.o

src/shared/state/Factory.i: src/shared/state/Factory.cpp.i

.PHONY : src/shared/state/Factory.i

# target to preprocess a source file
src/shared/state/Factory.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Factory.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Factory.cpp.i
.PHONY : src/shared/state/Factory.cpp.i

src/shared/state/Factory.s: src/shared/state/Factory.cpp.s

.PHONY : src/shared/state/Factory.s

# target to generate assembly for a file
src/shared/state/Factory.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Factory.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Factory.cpp.s
.PHONY : src/shared/state/Factory.cpp.s

src/shared/state/FieldObject.o: src/shared/state/FieldObject.cpp.o

.PHONY : src/shared/state/FieldObject.o

# target to build an object file
src/shared/state/FieldObject.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/FieldObject.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/FieldObject.cpp.o
.PHONY : src/shared/state/FieldObject.cpp.o

src/shared/state/FieldObject.i: src/shared/state/FieldObject.cpp.i

.PHONY : src/shared/state/FieldObject.i

# target to preprocess a source file
src/shared/state/FieldObject.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/FieldObject.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/FieldObject.cpp.i
.PHONY : src/shared/state/FieldObject.cpp.i

src/shared/state/FieldObject.s: src/shared/state/FieldObject.cpp.s

.PHONY : src/shared/state/FieldObject.s

# target to generate assembly for a file
src/shared/state/FieldObject.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/FieldObject.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/FieldObject.cpp.s
.PHONY : src/shared/state/FieldObject.cpp.s

src/shared/state/GameState.o: src/shared/state/GameState.cpp.o

.PHONY : src/shared/state/GameState.o

# target to build an object file
src/shared/state/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/GameState.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/GameState.cpp.o
.PHONY : src/shared/state/GameState.cpp.o

src/shared/state/GameState.i: src/shared/state/GameState.cpp.i

.PHONY : src/shared/state/GameState.i

# target to preprocess a source file
src/shared/state/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/GameState.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/GameState.cpp.i
.PHONY : src/shared/state/GameState.cpp.i

src/shared/state/GameState.s: src/shared/state/GameState.cpp.s

.PHONY : src/shared/state/GameState.s

# target to generate assembly for a file
src/shared/state/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/GameState.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/GameState.cpp.s
.PHONY : src/shared/state/GameState.cpp.s

src/shared/state/Headquarter.o: src/shared/state/Headquarter.cpp.o

.PHONY : src/shared/state/Headquarter.o

# target to build an object file
src/shared/state/Headquarter.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Headquarter.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Headquarter.cpp.o
.PHONY : src/shared/state/Headquarter.cpp.o

src/shared/state/Headquarter.i: src/shared/state/Headquarter.cpp.i

.PHONY : src/shared/state/Headquarter.i

# target to preprocess a source file
src/shared/state/Headquarter.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Headquarter.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Headquarter.cpp.i
.PHONY : src/shared/state/Headquarter.cpp.i

src/shared/state/Headquarter.s: src/shared/state/Headquarter.cpp.s

.PHONY : src/shared/state/Headquarter.s

# target to generate assembly for a file
src/shared/state/Headquarter.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Headquarter.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Headquarter.cpp.s
.PHONY : src/shared/state/Headquarter.cpp.s

src/shared/state/Installation.o: src/shared/state/Installation.cpp.o

.PHONY : src/shared/state/Installation.o

# target to build an object file
src/shared/state/Installation.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Installation.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Installation.cpp.o
.PHONY : src/shared/state/Installation.cpp.o

src/shared/state/Installation.i: src/shared/state/Installation.cpp.i

.PHONY : src/shared/state/Installation.i

# target to preprocess a source file
src/shared/state/Installation.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Installation.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Installation.cpp.i
.PHONY : src/shared/state/Installation.cpp.i

src/shared/state/Installation.s: src/shared/state/Installation.cpp.s

.PHONY : src/shared/state/Installation.s

# target to generate assembly for a file
src/shared/state/Installation.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Installation.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Installation.cpp.s
.PHONY : src/shared/state/Installation.cpp.s

src/shared/state/InstallationCard.o: src/shared/state/InstallationCard.cpp.o

.PHONY : src/shared/state/InstallationCard.o

# target to build an object file
src/shared/state/InstallationCard.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/InstallationCard.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/InstallationCard.cpp.o
.PHONY : src/shared/state/InstallationCard.cpp.o

src/shared/state/InstallationCard.i: src/shared/state/InstallationCard.cpp.i

.PHONY : src/shared/state/InstallationCard.i

# target to preprocess a source file
src/shared/state/InstallationCard.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/InstallationCard.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/InstallationCard.cpp.i
.PHONY : src/shared/state/InstallationCard.cpp.i

src/shared/state/InstallationCard.s: src/shared/state/InstallationCard.cpp.s

.PHONY : src/shared/state/InstallationCard.s

# target to generate assembly for a file
src/shared/state/InstallationCard.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/InstallationCard.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/InstallationCard.cpp.s
.PHONY : src/shared/state/InstallationCard.cpp.s

src/shared/state/Map.o: src/shared/state/Map.cpp.o

.PHONY : src/shared/state/Map.o

# target to build an object file
src/shared/state/Map.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Map.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Map.cpp.o
.PHONY : src/shared/state/Map.cpp.o

src/shared/state/Map.i: src/shared/state/Map.cpp.i

.PHONY : src/shared/state/Map.i

# target to preprocess a source file
src/shared/state/Map.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Map.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Map.cpp.i
.PHONY : src/shared/state/Map.cpp.i

src/shared/state/Map.s: src/shared/state/Map.cpp.s

.PHONY : src/shared/state/Map.s

# target to generate assembly for a file
src/shared/state/Map.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Map.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Map.cpp.s
.PHONY : src/shared/state/Map.cpp.s

src/shared/state/OilWell.o: src/shared/state/OilWell.cpp.o

.PHONY : src/shared/state/OilWell.o

# target to build an object file
src/shared/state/OilWell.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/OilWell.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/OilWell.cpp.o
.PHONY : src/shared/state/OilWell.cpp.o

src/shared/state/OilWell.i: src/shared/state/OilWell.cpp.i

.PHONY : src/shared/state/OilWell.i

# target to preprocess a source file
src/shared/state/OilWell.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/OilWell.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/OilWell.cpp.i
.PHONY : src/shared/state/OilWell.cpp.i

src/shared/state/OilWell.s: src/shared/state/OilWell.cpp.s

.PHONY : src/shared/state/OilWell.s

# target to generate assembly for a file
src/shared/state/OilWell.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/OilWell.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/OilWell.cpp.s
.PHONY : src/shared/state/OilWell.cpp.s

src/shared/state/Player.o: src/shared/state/Player.cpp.o

.PHONY : src/shared/state/Player.o

# target to build an object file
src/shared/state/Player.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Player.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Player.cpp.o
.PHONY : src/shared/state/Player.cpp.o

src/shared/state/Player.i: src/shared/state/Player.cpp.i

.PHONY : src/shared/state/Player.i

# target to preprocess a source file
src/shared/state/Player.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Player.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Player.cpp.i
.PHONY : src/shared/state/Player.cpp.i

src/shared/state/Player.s: src/shared/state/Player.cpp.s

.PHONY : src/shared/state/Player.s

# target to generate assembly for a file
src/shared/state/Player.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Player.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Player.cpp.s
.PHONY : src/shared/state/Player.cpp.s

src/shared/state/SupportCard.o: src/shared/state/SupportCard.cpp.o

.PHONY : src/shared/state/SupportCard.o

# target to build an object file
src/shared/state/SupportCard.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/SupportCard.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/SupportCard.cpp.o
.PHONY : src/shared/state/SupportCard.cpp.o

src/shared/state/SupportCard.i: src/shared/state/SupportCard.cpp.i

.PHONY : src/shared/state/SupportCard.i

# target to preprocess a source file
src/shared/state/SupportCard.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/SupportCard.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/SupportCard.cpp.i
.PHONY : src/shared/state/SupportCard.cpp.i

src/shared/state/SupportCard.s: src/shared/state/SupportCard.cpp.s

.PHONY : src/shared/state/SupportCard.s

# target to generate assembly for a file
src/shared/state/SupportCard.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/SupportCard.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/SupportCard.cpp.s
.PHONY : src/shared/state/SupportCard.cpp.s

src/shared/state/Tile.o: src/shared/state/Tile.cpp.o

.PHONY : src/shared/state/Tile.o

# target to build an object file
src/shared/state/Tile.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Tile.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Tile.cpp.o
.PHONY : src/shared/state/Tile.cpp.o

src/shared/state/Tile.i: src/shared/state/Tile.cpp.i

.PHONY : src/shared/state/Tile.i

# target to preprocess a source file
src/shared/state/Tile.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Tile.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Tile.cpp.i
.PHONY : src/shared/state/Tile.cpp.i

src/shared/state/Tile.s: src/shared/state/Tile.cpp.s

.PHONY : src/shared/state/Tile.s

# target to generate assembly for a file
src/shared/state/Tile.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Tile.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Tile.cpp.s
.PHONY : src/shared/state/Tile.cpp.s

src/shared/state/Tileset.o: src/shared/state/Tileset.cpp.o

.PHONY : src/shared/state/Tileset.o

# target to build an object file
src/shared/state/Tileset.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Tileset.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Tileset.cpp.o
.PHONY : src/shared/state/Tileset.cpp.o

src/shared/state/Tileset.i: src/shared/state/Tileset.cpp.i

.PHONY : src/shared/state/Tileset.i

# target to preprocess a source file
src/shared/state/Tileset.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Tileset.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Tileset.cpp.i
.PHONY : src/shared/state/Tileset.cpp.i

src/shared/state/Tileset.s: src/shared/state/Tileset.cpp.s

.PHONY : src/shared/state/Tileset.s

# target to generate assembly for a file
src/shared/state/Tileset.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Tileset.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Tileset.cpp.s
.PHONY : src/shared/state/Tileset.cpp.s

src/shared/state/Town.o: src/shared/state/Town.cpp.o

.PHONY : src/shared/state/Town.o

# target to build an object file
src/shared/state/Town.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Town.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Town.cpp.o
.PHONY : src/shared/state/Town.cpp.o

src/shared/state/Town.i: src/shared/state/Town.cpp.i

.PHONY : src/shared/state/Town.i

# target to preprocess a source file
src/shared/state/Town.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Town.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Town.cpp.i
.PHONY : src/shared/state/Town.cpp.i

src/shared/state/Town.s: src/shared/state/Town.cpp.s

.PHONY : src/shared/state/Town.s

# target to generate assembly for a file
src/shared/state/Town.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Town.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Town.cpp.s
.PHONY : src/shared/state/Town.cpp.s

src/shared/state/Unit.o: src/shared/state/Unit.cpp.o

.PHONY : src/shared/state/Unit.o

# target to build an object file
src/shared/state/Unit.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Unit.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Unit.cpp.o
.PHONY : src/shared/state/Unit.cpp.o

src/shared/state/Unit.i: src/shared/state/Unit.cpp.i

.PHONY : src/shared/state/Unit.i

# target to preprocess a source file
src/shared/state/Unit.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Unit.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Unit.cpp.i
.PHONY : src/shared/state/Unit.cpp.i

src/shared/state/Unit.s: src/shared/state/Unit.cpp.s

.PHONY : src/shared/state/Unit.s

# target to generate assembly for a file
src/shared/state/Unit.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Unit.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/Unit.cpp.s
.PHONY : src/shared/state/Unit.cpp.s

src/shared/state/UnitCard.o: src/shared/state/UnitCard.cpp.o

.PHONY : src/shared/state/UnitCard.o

# target to build an object file
src/shared/state/UnitCard.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/UnitCard.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/UnitCard.cpp.o
.PHONY : src/shared/state/UnitCard.cpp.o

src/shared/state/UnitCard.i: src/shared/state/UnitCard.cpp.i

.PHONY : src/shared/state/UnitCard.i

# target to preprocess a source file
src/shared/state/UnitCard.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/UnitCard.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/UnitCard.cpp.i
.PHONY : src/shared/state/UnitCard.cpp.i

src/shared/state/UnitCard.s: src/shared/state/UnitCard.cpp.s

.PHONY : src/shared/state/UnitCard.s

# target to generate assembly for a file
src/shared/state/UnitCard.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/UnitCard.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/shared/state/UnitCard.cpp.s
.PHONY : src/shared/state/UnitCard.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/client/render/EventController.o"
	@echo "... src/client/render/EventController.i"
	@echo "... src/client/render/EventController.s"
	@echo "... src/client/render/GFieldObject.o"
	@echo "... src/client/render/GFieldObject.i"
	@echo "... src/client/render/GFieldObject.s"
	@echo "... src/client/render/GMap.o"
	@echo "... src/client/render/GMap.i"
	@echo "... src/client/render/GMap.s"
	@echo "... src/client/render/GPlayer.o"
	@echo "... src/client/render/GPlayer.i"
	@echo "... src/client/render/GPlayer.s"
	@echo "... src/client/render/GRender.o"
	@echo "... src/client/render/GRender.i"
	@echo "... src/client/render/GRender.s"
	@echo "... src/client/render/GState.o"
	@echo "... src/client/render/GState.i"
	@echo "... src/client/render/GState.s"
	@echo "... src/client/render/TextureManager.o"
	@echo "... src/client/render/TextureManager.i"
	@echo "... src/client/render/TextureManager.s"
	@echo "... src/client/tests.o"
	@echo "... src/client/tests.i"
	@echo "... src/client/tests.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
	@echo "... src/shared/ai/CPU.o"
	@echo "... src/shared/ai/CPU.i"
	@echo "... src/shared/ai/CPU.s"
	@echo "... src/shared/ai/DeepCPU.o"
	@echo "... src/shared/ai/DeepCPU.i"
	@echo "... src/shared/ai/DeepCPU.s"
	@echo "... src/shared/ai/DeepCPU_2.o"
	@echo "... src/shared/ai/DeepCPU_2.i"
	@echo "... src/shared/ai/DeepCPU_2.s"
	@echo "... src/shared/ai/HeuristicCPU.o"
	@echo "... src/shared/ai/HeuristicCPU.i"
	@echo "... src/shared/ai/HeuristicCPU.s"
	@echo "... src/shared/ai/RandomCPU.o"
	@echo "... src/shared/ai/RandomCPU.i"
	@echo "... src/shared/ai/RandomCPU.s"
	@echo "... src/shared/engine/Command.o"
	@echo "... src/shared/engine/Command.i"
	@echo "... src/shared/engine/Command.s"
	@echo "... src/shared/engine/CommandEndTurn.o"
	@echo "... src/shared/engine/CommandEndTurn.i"
	@echo "... src/shared/engine/CommandEndTurn.s"
	@echo "... src/shared/engine/CommandMove.o"
	@echo "... src/shared/engine/CommandMove.i"
	@echo "... src/shared/engine/CommandMove.s"
	@echo "... src/shared/engine/GameEngine.o"
	@echo "... src/shared/engine/GameEngine.i"
	@echo "... src/shared/engine/GameEngine.s"
	@echo "... src/shared/state/Building.o"
	@echo "... src/shared/state/Building.i"
	@echo "... src/shared/state/Building.s"
	@echo "... src/shared/state/Card.o"
	@echo "... src/shared/state/Card.i"
	@echo "... src/shared/state/Card.s"
	@echo "... src/shared/state/Cards.o"
	@echo "... src/shared/state/Cards.i"
	@echo "... src/shared/state/Cards.s"
	@echo "... src/shared/state/Deck.o"
	@echo "... src/shared/state/Deck.i"
	@echo "... src/shared/state/Deck.s"
	@echo "... src/shared/state/EquipmentCard.o"
	@echo "... src/shared/state/EquipmentCard.i"
	@echo "... src/shared/state/EquipmentCard.s"
	@echo "... src/shared/state/Factory.o"
	@echo "... src/shared/state/Factory.i"
	@echo "... src/shared/state/Factory.s"
	@echo "... src/shared/state/FieldObject.o"
	@echo "... src/shared/state/FieldObject.i"
	@echo "... src/shared/state/FieldObject.s"
	@echo "... src/shared/state/GameState.o"
	@echo "... src/shared/state/GameState.i"
	@echo "... src/shared/state/GameState.s"
	@echo "... src/shared/state/Headquarter.o"
	@echo "... src/shared/state/Headquarter.i"
	@echo "... src/shared/state/Headquarter.s"
	@echo "... src/shared/state/Installation.o"
	@echo "... src/shared/state/Installation.i"
	@echo "... src/shared/state/Installation.s"
	@echo "... src/shared/state/InstallationCard.o"
	@echo "... src/shared/state/InstallationCard.i"
	@echo "... src/shared/state/InstallationCard.s"
	@echo "... src/shared/state/Map.o"
	@echo "... src/shared/state/Map.i"
	@echo "... src/shared/state/Map.s"
	@echo "... src/shared/state/OilWell.o"
	@echo "... src/shared/state/OilWell.i"
	@echo "... src/shared/state/OilWell.s"
	@echo "... src/shared/state/Player.o"
	@echo "... src/shared/state/Player.i"
	@echo "... src/shared/state/Player.s"
	@echo "... src/shared/state/SupportCard.o"
	@echo "... src/shared/state/SupportCard.i"
	@echo "... src/shared/state/SupportCard.s"
	@echo "... src/shared/state/Tile.o"
	@echo "... src/shared/state/Tile.i"
	@echo "... src/shared/state/Tile.s"
	@echo "... src/shared/state/Tileset.o"
	@echo "... src/shared/state/Tileset.i"
	@echo "... src/shared/state/Tileset.s"
	@echo "... src/shared/state/Town.o"
	@echo "... src/shared/state/Town.i"
	@echo "... src/shared/state/Town.s"
	@echo "... src/shared/state/Unit.o"
	@echo "... src/shared/state/Unit.i"
	@echo "... src/shared/state/Unit.s"
	@echo "... src/shared/state/UnitCard.o"
	@echo "... src/shared/state/UnitCard.i"
	@echo "... src/shared/state/UnitCard.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

