// Generated by dia2code
#ifndef RENDER__CURSOR__H
#define RENDER__CURSOR__H

#include <SFML/Graphics.hpp>

namespace sf {
  class Drawable;
}


namespace render {

  /// class Cursor - 
  class Cursor : public sf::Drawable {
    // Attributes
  public:
    sf::Color color;
    unsigned int size;
    sf::Vector2u position;
    // Operations
  public:
    Cursor (unsigned int size, sf::Vector2u position);
    Cursor (unsigned int size, sf::Vector2u position, sf::Color color);
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
  };

};

#endif
