// Generated by dia2code
#ifndef RENDER__EVENTCONTROLLER__H
#define RENDER__EVENTCONTROLLER__H

#include <memory>
#include <SFML/Graphics.hpp>

namespace engine {
  class GameEngine;
}

#include "engine/GameEngine.h"

namespace render {

  /// class EventController - 
  class EventController {
    // Associations
    // Attributes
  public:
    bool shiftPressed;
    bool controlPressed;
    bool altPressed;
    // Operations
  public:
    EventController ();
    void handle (sf::Event& event, std::shared_ptr<engine::GameEngine> engine, sf::RenderWindow& window, bool& displayWindow);
    void zoomViewAt (sf::Vector2i pixel, sf::RenderWindow&  window, float zoom);
  };

};

#endif
