// Generated by dia2code
#ifndef RENDER__EVENTCONTROLLER__H
#define RENDER__EVENTCONTROLLER__H

#include <memory>
#include <SFML/Graphics.hpp>

namespace engine {
  class GameEngine;
};
namespace render {
  class GRender;
}

#include "engine/GameEngine.h"
#include "GRender.h"

namespace render {

  /// class EventController - 
  class EventController {
    // Associations
    // Attributes
  public:
    bool shiftPressed;
    bool controlPressed;
    bool altPressed;
    // Operations
  public:
    EventController ();
    void handle (sf::Event& event, std::shared_ptr<engine::GameEngine> engine,  std::shared_ptr<GRender>  render, bool& displayWindow);
    void updateCursor (sf::Vector2i pixel, std::shared_ptr<GRender> render);
    void zoomViewAt (sf::Vector2i pixel, std::shared_ptr<sf::RenderWindow> window, float zoom);
  };

};

#endif
