// Generated by dia2code
#ifndef RENDER__GFIELDOBJECT__H
#define RENDER__GFIELDOBJECT__H

#include <memory>

namespace sf {
  class Drawable;
};
namespace state {
  class Tileset;
}

#include "state/Tileset.h"

namespace render {

  /// class GFieldObject - 
  class GFieldObject : public sf::Drawable {
    // Associations
    // Attributes
  private:
    std::shared_ptr<state::FieldObject> fieldObject;
    static state::Tileset buildingsTileset;
    static state::Tileset unitsTileset;
    // Operations
  public:
    GFieldObject (std::shared_ptr<state::FieldObject> fieldObject);
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
  };

};

#endif
