// Generated by dia2code
#ifndef RENDER__GFIELDOBJECT__H
#define RENDER__GFIELDOBJECT__H

#include <SFML/Graphics.hpp>

namespace state {
  class FieldObject;
}

#include "state/FieldObject.h"

namespace render {

  /// class GFieldObject - 
  class GFieldObject {
    // Associations
    // Attributes
  private:
    sf::Vector2f position;
    sf::Sprite sprite;
    int id;
    // Operations
  public:
    GFieldObject ();
    void setSprite (state::FieldObject * fieldobject);
    void setPosition (state::FieldObject * fieldobject);
  };

};

#endif
