// Generated by dia2code
#ifndef RENDER__GFIELDOBJECT__H
#define RENDER__GFIELDOBJECT__H

#include <memory>

namespace sf {
  class Drawable;
}


namespace render {

  /// class GFieldObject - 
  class GFieldObject : public sf::Drawable {
    // Attributes
  public:
    std::shared_ptr<state::FieldObject> fieldObject;
    // Operations
  public:
    GFieldObject (std::shared_ptr<state::FieldObject> fieldObject);
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
  };

};

#endif
