// Generated by dia2code
#ifndef RENDER__GMAP__H
#define RENDER__GMAP__H

#include <memory>

namespace sf {
  class Drawable;
};
namespace state {
  class GameState;
}

#include "state/GameState.h"

namespace render {

  /// class GMap - 
  class GMap : public sf::Drawable {
    // Associations
    // Attributes
  private:
    std::shared_ptr<state::Map> map;
    // Operations
  public:
    GMap (std::shared_ptr<state::Map> map);
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
  };

};

#endif
