// Generated by dia2code
#ifndef RENDER__GMAP__H
#define RENDER__GMAP__H


namespace sf {
  class Drawable;
};
namespace state {
  class GameState;
}

#include "state/GameState.h"

namespace render {

  /// class GMap - 
  class GMap : public sf::Drawable {
    // Associations
    // Operations
  public:
    GMap ();
    void draw (sf::RenderTarget& target, sf::RenderStates states);
  };

};

#endif
