// Generated by dia2code
#ifndef RENDER__GRENDER__H
#define RENDER__GRENDER__H


namespace render {

  /// class GRender - 
  class GRender {
    // Operations
  public:
    GRender ();
    void display (state::GameState s);
  };

};

#endif
