// Generated by dia2code
#ifndef RENDER__GRENDER__H
#define RENDER__GRENDER__H

#include <SFML/Graphics.hpp>

namespace render {
  class GState;
};
namespace state {
  class GameState;
}

#include "GState.h"
#include "state/GameState.h"

namespace render {

  /// class GRender - 
  class GRender {
    // Associations
    // Attributes
  public:
    sf::RenderWindow window;
    // Operations
  public:
    GRender ();
    void display (GState& g);
  };

};

#endif
