// Generated by dia2code
#ifndef RENDER__GSTATE__H
#define RENDER__GSTATE__H

#include <memory>
#include <vector>

namespace state {
  class GameState;
};
namespace render {
  class GMap;
  class GPlayer;
}

#include "state/GameState.h"
#include "GMap.h"
#include "GPlayer.h"

namespace render {

  /// class GState - 
  class GState {
    // Associations
    // Attributes
  private:
    std::shared_ptr<state::GameState> state;
    GMap gmap;
    std::vector<GPlayer> gplayers;
    // Operations
  public:
    GState (std::shared_ptr<state::GameState> state);
    GMap& getGMap ();
    std::vector<GPlayer>& getGPlayers ();
    unsigned int getTurn ();
    unsigned int getPlayerCount ();
  };

};

#endif
