// Generated by dia2code
#ifndef RENDER__GSTATE__H
#define RENDER__GSTATE__H


namespace render {
  class GMap;
  class GFieldObject;
}

#include "GMap.h"
#include "GFieldObject.h"

namespace render {

  /// class GState - 
  class GState {
    // Associations
    // Attributes
  private:
    state::GameState state;
    state::FieldObjects fieldobjects;
    // Operations
  public:
    GState (state::GameState s);
  };

};

#endif
