// Generated by dia2code
#ifndef RENDER__GSTATE__H
#define RENDER__GSTATE__H

#include <memory>

namespace render {
  class GMap;
};
namespace state {
  class GameState;
  class FieldObjects;
};
namespace render {
  class GFieldObject;
}

#include "GMap.h"
#include "state/GameState.h"
#include "state/FieldObjects.h"
#include "GFieldObject.h"

namespace render {

  /// class GState - 
  class GState {
    // Associations
    // Attributes
  public:
    GMap gmap;
  private:
    std::shared_ptr<state::GameState> state;
    state::FieldObjects fieldobjects;
    // Operations
  public:
    GState (std::shared_ptr<state::GameState> state);
    GMap& getGMap ();
  };

};

#endif
