// Generated by dia2code
#ifndef RENDER__TEXTUREMANAGER__H
#define RENDER__TEXTUREMANAGER__H

#include <string>
#include <map>
#include <SFML/Graphics.hpp>

namespace render {

  /// class TextureManager - 
  class TextureManager {
    // Attributes
  private:
    static  std::map<std::string, sf::Texture*> textures;
     static std::vector<std::string> order;
    // Operations
  public:
    TextureManager ();
    ~TextureManager ();
    static int getLength ();
    static sf::Texture * getTexture (std::string name);
    static sf::Texture * getTexture (int index);
    static sf::Texture * loadTexture (std::string name, std::string path);
  };

};

#endif
