// Generated by dia2code
#ifndef REST__SERVICEEXCEPTION__H
#define REST__SERVICEEXCEPTION__H

#include <string>

namespace rest {
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"

namespace rest {

  /// class ServiceException - 
  class ServiceException {
    // Associations
    rest::HttpStatus httpStatus;
    // Attributes
  protected:
    std::string msg;
    // Operations
  public:
    ServiceException (HttpStatus status, std::string msg);
    HttpStatus status () const;
    const char* what () const;
  };

};

#endif
