// Generated by dia2code
#ifndef REST__VERSIONSERVICE__H
#define REST__VERSIONSERVICE__H

#include <json/json.h>

namespace rest {
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"

namespace rest {

  /// class VersionService - 
  class VersionService : public rest::AbstractService {
    // Operations
  public:
    VersionService ();
    HttpStatus get (Json::Value& out, int id) const;
  };

};

#endif
