// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "render/GFieldObject.h"
#include "render/GMap.h"
#include "render/GState.h"
#include "render/GRender.h"
#include "render/TextureManager.h"
#endif
